language: node_js
node_js:
  - "14"
branchs:
  only:
    - master
install:
  - echo "install successed"
os:
  - linux

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - git clone https://${GH_REF}
        - cd react-dark-photo
        - git branch
        - git checkout travis
        - git rebase master
        - npm version patch
        - npm install --registry=https://registry.npm.taobao.org
        - npm run build
        - cp -f package.json ./
        - echo "NPM Building Finished."
      deploy: 
        provider: npm
        email: "502342826@qq.com"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
      after_script:
        - git config user.name "travis"
        - git config user.email "502342826@qq.com"
        - git add .
        - git commit -m "Travis CI Auto Builder"
        - git status
        - git push "https://${GH_TOKEN}@${GH_REF}" travis:travis
        - git checkout master
        - git rebase travis
        - git push "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - master
    